[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "foundry-devops/=lib/foundry-devops/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

optimizer = true
optimizer_runs = 200
evm_version = "london"
# Uncomment the line below to enable automatic test fuzzing
# fuzz = true

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
